
NODES = [
  { name: "bob01", ip: "192.0.2.2" },
  { name: "bob02", ip: "192.0.2.3" },
  { name: "bob03", ip: "192.0.2.4" },
]

GROUPS = {
  "all"          => ["bob01", "bob02", "bob03"],
  "swarm_master" => ["bob02"],
}


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  NODES.each do |node_spec|
    config.vm.define node_spec[:name], autostart: true do |node|
      node.vm.network "private_network", ip: node_spec[:ip]
      node.vm.hostname = node_spec[:name]

      node.vm.provision "shell", inline: "apt-get -y install python-minimal"

      if node_spec[:name] == "bob03"

        node.vm.provision "ansible" do |ansible|
          ansible.verbose = "1"
          ansible.limit = "all"
          ansible.playbook = "playbook.yml"
          ansible.galaxy_roles_path = "roles"
          ansible.groups = GROUPS
        end
      end
    end
  end

end
