---

- name: generate GB locale
  become: true
  locale_gen:
    name: "{{ bobnet_locale }}"
    state: present

- name: add locale as default
  become: true
  copy:
    dest: /etc/default/locale
    content: |
      LANG={{ bobnet_locale }}

- name: update apt caches
  apt: upgrade=yes update_cache=yes cache_valid_time=86400
  become: true

- name: add useful tools
  package: name={{item}} state=latest
  with_items:
    - dnsutils
    - htop
    - tmux
    - vim
  become: true

- name: "Ensure docker is installed"
  become: true
  package:
    name: "{{ bobnet_docker_package }}"
    state: latest

- name: "Add ansible to groups"
  become: true
  user:
    name: "{{ bobnet_ansible_user }}"
    append: true
    groups:
      - docker

- name: "Wait for docker service to start"
  become: true
  shell: "docker info"
  register: result
  until: result.rc == 0
  retries: 5
  delay: 5
