---

- debug: var=group_names

- set_fact:
    master_address: "{{ bobnet_networking[groups['swarm_master'][0]].eth0_ipv4_address }}"

- name: "Get swarm status"
  shell: "docker info | grep '^Swarm:' | awk '{print $2}'"
  register: swarm_status

- name: "Initialise swarm"
  command: "docker swarm init --advertise-addr={{ master_address }}:2377"
  when: "'swarm_master' in group_names and 'inactive' == swarm_status.stdout"

- name: "Get swarm worker token"
  command: "docker swarm join-token -q worker"
  register: swarm_worker_token
  when: "'swarm_master' in group_names"

- set_fact:
    worker_token: "{{ hostvars[groups['swarm_master'][0]].swarm_worker_token.stdout }}"

- name: "Join worker node"
  command: "docker swarm join --advertise-addr=eth0:2377 --token={{ worker_token }} {{ master_address }}:2377"
  when: "'swarm_master' not in group_names and 'inactive' == swarm_status.stdout"

- name: "Add node labels"
  command: "docker node update --label-add {{ item.1 }} {{ item.0.host }}"
  with_subelements:
    - "{{ bobnet_swarm_labels }}"
    - "labels"
  when: "'swarm_master' in group_names"
